Refactor module code

diff --git a/czhttpd b/czhttpd
--- a/czhttpd
+++ b/czhttpd
@@ -44,7 +44,6 @@ typeset -a LOG_FORMAT
 
 # Internal function variables that need global scope
 typeset -A req_headers
-typeset -a listing
 
 # Functions
 function error() {
@@ -151,7 +150,8 @@ function parse_conf() {
         . $1 || print "Could not source config file $1"
     fi
 
-    if ! (($logfd + $errfd)); then
+    # If unset `logfd, errfd = 0`
+    if ! (( $logfd + $errfd )); then
         if [[ -n $LOG_DIR ]]; then
             if [[ $LOG_DIR == "/dev/null" ]]; then
                 exec {logfd}>/dev/null {errfd}>/dev/null
@@ -187,10 +187,7 @@ function parse_args() {
     zparseopts -K -D -A opts c: p: h v || error 2>/dev/null
 
     [[ -n ${(kM)opts:#-h} ]] && help
-    if [[ -n ${(kM)opts:#-v} ]]; then
-        ! (( $logfd + $errfd )) && exec {errfd}>&1 {logfd}>&1
-    fi
-
+    [[ -n ${(kM)opts:#-v} ]] && exec {errfd}>&1 {logfd}>&1
     [[ -n $opts[-c] && ! -f $opts[-c] ]] && error "Config file $opts[-c] does not exist"
     parse_conf ${opts[-c]:-~/.config/czhttpd/conf/main.conf}
     [[ -n $opts[-p] ]] && PORT=$opts[-p]
@@ -313,7 +310,7 @@ function html_template() {
 }
 
 function html_fragment() {
-    listing+="<tr><td><a href=\"${1#*/}\">${1#*/}</a></td><td>$(mtime $1)</td><td>$(calc_size $1)</td><td>$(mime_type $1)</td></tr>"
+    index+="<tr><td><a href=\"${1#*/}\">${1#*/}</a></td><td>$(mtime $1)</td><td>$(calc_size $1)</td><td>$(mime_type $1)</td></tr>"
 }
 
 function urldecode() {
@@ -367,10 +364,8 @@ function mtime() {
     stat -L -F "%d-%b-%Y %H:%M" +mtime $1 2>/dev/null || print "\-"
 }
 
-function list_dir() {
-    # Return a global array
-    # Ugly I know, but global vars are quicker
-    unset listing; typeset -ga listing
+function build_index() {
+    local -a index
     local i
 
     cd "$1"
@@ -388,6 +383,8 @@ function list_dir() {
     done
 
     cd -
+
+    html_template "$1" $index
 }
 
 function spawn_cache_worker() {
@@ -416,40 +413,6 @@ function spawn_cache_worker() {
             unset lockfile cache_file
         done < <(fswatch -r $DOCROOT)
     done) &
-
-    print $!
-}
-
-### send_list - dynamically list directory contents
-# - list_dir fills a global array 'listing' with a html fragment for each file/dir
-# - Pass `listing` as an argument to html_template and redirect output
-# - Search for a filter that may want to handle output (ie compression)
-# - Or, send our html page as plaintext using chunked encoding (hopefully improves latency)
-function send_list() {
-    local mtype="text/html"
-
-    if (( $CACHE == 1 )); then
-        local lockfile="${CACHE_DIR}/${1:gs/\//.}"
-        local cache_file="${lockfile%.}.html"
-        mklock $lockfile
-
-        # Definitely slower than multios, but easier to deal with compression
-        if [[ ! -f $cache_file ]]; then
-            list_dir $1
-            html_template $1 $listing > $cache_file
-        fi
-
-        cd $CACHE_DIR
-        { default_handler ${cache_file:t} } always { cd -; rmdir $lockfile }
-    else
-        list_dir $1
-
-        if ! filter_search $1; then
-            return_header "200 Ok" "Content-type: $mtype; charset=UTF-8" "Transfer-Encoding: chunked"
-            send_chunk
-            log_f "200"
-        fi < <(html_template $1 $listing)
-    fi
 }
 
 function send_file() {
@@ -473,44 +436,40 @@ function send_chunk() {
     fi
 }
 
-### default_handler
-# Our default handler to simply send requested file to client
-function default_handler() {
-    # Save mime-type and size to local vars so that our filter modules can inherit them
-    [[ -z $mtype ]] && local mtype=$(mime_type $1)
-    local fsize=$(stat -L +size $1)
-
-    # Find a filter, e.g. to compress output, if not send raw file
-    if ! filter_search $1; then
+function __send() {
+    if [[ -f $1 ]]; then
         return_header "200 Ok" "Content-type: $mtype; charset=UTF-8" "Content-Length: $fsize"
         send_file $1
+    else
+        return_header "200 Ok" "Content-type: $mtype; charset=UTF-8" "Transfer-Encoding: chunked"
+        send_chunk
     fi
 
     log_f "200"
 }
 
-### filter_search
-# How to handle output stream
-function filter_search() {
-    local i
+function __file_handler() {
+    [[ -z $mtype ]] && local mtype=$(mime_type $1)
+    local fsize=$(stat -L +size $1)
 
-    for i in ${(Mk)functions#*_filter}; { $i $1 && return }
-
-    return 1
+    send $1
 }
 
-### handler_search
-# How to handle a requested file (send or exec?)
-function handler_search() {
-    local i
+function __dir_handler() {
+    local mtype="text/html"
 
-    for i in ${(Mk)functions#*_handler}; do
-        if [[ $i != "default_handler" ]]; then
-            $i $1 && return
-        fi
-    done
+    if (( $CACHE )); then
+        local lockfile="${CACHE_DIR}/${1:gs/\//.}"
+        local cache_file="${lockfile%.}.html"
+        mklock $lockfile
 
-    return 1
+        [[ ! -f $cache_file ]] && build_index $1 > $cache_file
+
+        cd $CACHE_DIR
+        { file_handler ${cache_file:t} } always { cd -; rmdir $lockfile }
+    else
+        send < <(build_index $1)
+    fi
 }
 
 function srv() {
@@ -521,21 +480,16 @@ function srv() {
     [[ $FOLLOW_SYMLINKS != "1" && -h ${pathname%/} ]] && { error_header 403; return }
 
     if [[ -f ${pathname%/} ]]; then
-        # Find a handler for $pathname (e.g. to handle cgi), if not use the default
-        if ! handler_search $pathname; then
-            default_handler $pathname
-        fi
+        file_handler $pathname
     elif [[ -d $pathname ]]; then
         if [[ -f $pathname/$INDEX_FILE ]]; then
-            if ! handler_search $pathname/$INDEX_FILE; then
-                default_handler $pathname/$INDEX_FILE
-            fi
+            file_handler $pathname/$INDEX_FILE
         else
             if [[ $pathname != $DOCROOT && $pathname[-1] != "/" ]]; then
                 error_header 301 "http://$SERVER_ADDR:$PORT${pathname#$DOCROOT}/"
                 return
             elif [[ -r "$pathname" && -x "$pathname" ]]; then
-                send_list "$pathname"
+                dir_handler "$pathname"
             else
                 error_header 403
             fi
@@ -549,13 +503,12 @@ function srv() {
 function cleanup() {
     setopt noerrreturn
     for i in ${(SM)jobstates##<->}; do
-        kill -9 $i
+        kill -15 $i
     done
 
     log_f "> Exiting main"
-    exec {logfd}>&-; exec {errfd}>&-
-    exec {fifofd}>&-
-    rm $FIFO; rm -rf $CACHE_DIR
+    exec {logfd}>&- {errfd}>&- {fifofd}>&-
+    rm -rf $FIFO $CACHE_DIR
     ztcp -c
 }
 
@@ -571,6 +524,10 @@ function czhttpd_init() {
 
     # Parse cli options and config file
     parse_args $*
+
+    ! typeset -f send >/dev/null && send() { __send $* }
+    ! typeset -f file_handler >/dev/null && file_handler() { __file_handler $* }
+    ! typeset -f dir_handler >/dev/null && dir_handler() { __dir_handler $* }
 
     # Set our default variables
     log_f "MAXCONN: ${MAX_CONN:=12}"
@@ -621,10 +578,13 @@ function czhttpd_init() {
     # For communication with our child processes
     FIFO=$FIFO_DIR/czhttpd-$$.fifo
     [[ ! -p $FIFO ]] && { mkfifo $FIFO || error "Can not create fifo, $FIFO" }
-    ! (( $fifofd )) && exec {fifofd}<>$FIFO
+    exec {fifofd}<>$FIFO
 
     # For monitoring when our cache becomes invalid
-    (( $CACHE )) && { CACHE_WORKER_PID=$(spawn_cache_worker) || error "Failed to initialise cache_worker" }
+    if (( $CACHE )); then
+        spawn_cache_worker || error "Failed to initialise cache_worker"
+        CACHE_WORKER_PID=$!
+    fi
 
     return 0
 }
@@ -669,7 +629,7 @@ function czhttpd_main() {
         exec {OLD_FIFO_FD}>&-
         unset OLD_FIFO OLD_FIFO_FD OLD_PIDS
 
-        # Must use replace with exec, otherwise interrupting
+        # Must replace process with exec, otherwise interrupting
         # ztcp -a will crash czhttpd.
         exec czhttpd_main
     }
@@ -679,15 +639,14 @@ function czhttpd_main() {
 
     while :; do
         # Use select to block until a child writes to fifo on exit
-        while (( ${#jobstates} >= $MAX_CONN - $CACHE )); do
+        while (( ${#jobstates} >= $MAX_CONN + $CACHE )); do
             log_f "max connections hit, temporarily unable to fork"
             zselect -r $fifofd && break
         done
 
         ztcp -a $listenfd
 
-        ( trap "child_cleanup 2>/dev/null" KILL TERM EXIT; trap '' CHLD HUP PIPE
-
+        ( trap "child_cleanup 2>/dev/null" KILL TERM EXIT; trap '' PIPE; trap - HUP
         function child_cleanup() {
             kill -9 $coproc_pid; ztcp -c
             print "0" >&$fifofd
@@ -697,7 +656,7 @@ function czhttpd_main() {
 
         # Use coproc to filter stderr from `srv` and preserve proper pid
         # for logs.
-        coproc { for ((;;)); zselect -r 0 && <&0 }
+        coproc { while true; do; zselect -r 0 && <&0; done }
         coproc_pid=$!
 
         while read ip_line; do
