Rework config reload; fix srv err logging bug

diff --git a/czhttpd b/czhttpd
--- a/czhttpd
+++ b/czhttpd
@@ -28,14 +28,13 @@ zmodload zsh/zselect
 ### zsh options
 # unset:
 #   multibyte - to accurately get length of utf8 strings
-#   multios - prevent duplication of stderr when logging output of `srv`
 #   glob_dots - prevent iterating through dot files automatically
 # set:
 #   posix_jobs - for handling jobs in communicating parent<-child
 #   err_return - handle errors @ highest calling level
 #   bare_glob_qual - required for our patterns in `list_dir`
-unsetopt multibyte multios glob_dots
-setopt posix_jobs err_return bare_glob_qual local_options
+unsetopt multibyte glob_dots err_return
+setopt posix_jobs bare_glob_qual local_options
 
 # Declare variable types
 integer logfd errfd fifofd
@@ -49,7 +48,6 @@ typeset -a listing
 
 # Functions
 function error() {
-    setopt multios
     print "[$(strftime "%a %d %b, %H:%M:%S" $EPOCHSECONDS)] Fatal Error: $*" >&2 >&$errfd
 
     cleanup 2>/dev/null
@@ -215,9 +213,14 @@ function http_listen() {
     typeset -g listenfd
 
     if (( $PORT > 1024 )); then
-        ztcp -l $PORT 2>/dev/null || error "Could not bind to port $PORT"
-        print "Listening on $PORT"
-        listenfd=$REPLY
+        if [[ $PORT != $OLD_PORT ]]; then
+            ztcp -c
+            ztcp -l $PORT 2>/dev/null || error "Could not bind to port $PORT"
+            print "Listening on $PORT"
+            listenfd=$REPLY
+        fi
+
+        unset OLD_PORT
     else
         error "Invalid port number, $PORT"
     fi
@@ -515,6 +518,7 @@ function handler_search() {
 }
 
 function srv() {
+    setopt err_return
     local pathname="${DOCROOT}$(urldecode $req_headers[url])"
 
     [[ $HIDDEN_FILES != "1" && ${pathname:t} == .* ]] && { error_header 403; return }
@@ -549,7 +553,7 @@ function srv() {
 function cleanup() {
     setopt noerrreturn
     for i in ${(SM)jobstates##<->}; do
-        kill $i
+        kill -9 $i
     done
 
     log_f "> Exiting main"
@@ -559,139 +563,165 @@ function cleanup() {
     ztcp -c
 }
 
-### TRAPCHLD
-# Run this function as a trap rather than in main() so that we trigger a flush
-# when ${#jobstates} < $MAX_CONN
-function TRAPCHLD() {
-    while sysread -t 0 -i $fifofd -o 1 1>/dev/null; do
-        continue
+#### Main
+function czhttpd_init() {
+    ARGV="$*"
+    LOG_FORMAT=( '[$(strftime "%a %d %b, %H:%M:%S" $EPOCHSECONDS)]'
+                 '[pid: $sysparams[pid]]'
+                 '$client_ip'
+                 '$req_headers[method]'
+                 '$req_headers[url]'
+                 '$req_headers[version]' )
+
+    # Parse cli options and config file
+    parse_args $*
+
+    # Set our default variables
+    log_f "MAXCONN: ${MAX_CONN:=12}"
+    log_f "PORT: ${PORT:=8080}"
+    log_f "IP_REDIRECT: ${IP_REDIRECT:=$(ip_addr)}"
+    log_f "IP_ACCEPT: ${IP_ACCEPT:=[0-9*].[0-9*].[0-9*].[0-9*]}"
+    log_f "HTTP_KEEP_ALIVE: ${HTTP_KEEP_ALIVE:=1}"
+    log_f "HTTP_TIMEOUT: ${HTTP_TIMEOUT:=30}"
+    log_f "INDEX_FILE: ${INDEX_FILE:=index.html}"
+    log_f "HIDDEN_FILES: ${HIDDEN_FILES:=0}"
+    log_f "FOLLOW_SYMLINKS: ${FOLLOW_SYMLINKS:=0}"
+    log_f "CACHE: ${CACHE:=0}"
+    log_f "CACHE_DIR: ${CACHE_DIR:=/tmp/.czhttpd-$$/}"
+    log_f "LOG_DIR: ${LOG_DIR:=/dev/null}"
+    log_f "FIFO_DIR: ${FIFO_DIR:=/tmp}"
+
+    readonly SERVER_NAME="$IP_REDIRECT"
+    readonly SERVER_ADDR="$SERVER_NAME"
+    readonly SERVER_SOFTWARE="czhttpd/$(printf '%.1f\n' "$((RANDOM/10000.0))")b"
+    readonly SERVER_PROTOCOL="HTTP/1.1"
+    readonly GATEWAY_INTERFACE="CGI/1.1"
+
+    if [[ -z $MTYPES ]]; then
+        MTYPES=( pdf       application/pdf
+                 gz        application/x-gzip
+                 tar.gz    application/x-tgz
+                 tgz       application/x-tgz
+                 tar       application/x-tar
+                 zip       application/zip
+                 gif       image/gif
+                 jpeg      image/jpeg
+                 jpg       image/jpeg
+                 png       image/png
+                 css       text/css
+                 html      text/html
+                 htm       text/html
+                 js        text/javascript
+                 sh        text/plain
+                 py        text/plain
+                 pl        text/plain
+                 log       text/plain
+                 conf      text/plain
+                 text      text/plain
+                 txt       text/plain
+                 default   application/octet-stream )
+    fi
+
+    # For communication with our child processes
+    FIFO=$FIFO_DIR/czhttpd-$$.fifo
+    [[ ! -p $FIFO ]] && { mkfifo $FIFO || error "Can not create fifo, $FIFO" }
+    exec {fifofd}<>$FIFO
+
+    # For monitoring when our cache becomes invalid
+    (( $CACHE )) && { CACHE_WORKER_PID=$(spawn_cache_worker) || error "Failed to initialise cache_worker" }
+
+    return 0
+}
+
+function czhttpd_main() {
+    # Run this function as a trap so that we trigger a flush
+    # when ${#jobstates} < $MAX_CONN
+    function TRAPCHLD() {
+        while sysread -t 0 -i $fifofd -o 1 1>/dev/null; do
+            continue
+        done
+    }
+
+    function TRAPHUP() {
+        log_f "Reloading..."
+
+        if kill -0 $CACHE_WORKER_PID 2>/dev/null; then
+            kill -15 $CACHE_WORKER_PID 2>/dev/null
+        fi
+
+        OLD_PORT=$PORT
+        OLD_FIFO=$FIFO
+        OLD_FIFO_FD=$fifofd
+        czhttpd_init ${=ARGV}
+
+        if [[ $OLD_FIFO != $FIFO ]]; then
+            rm $OLD_FIFO
+            OLD_PIDS=(${(SM)jobstates##<->})
+            if [[ -n $OLD_PIDS ]]; then
+                ( while sysread -i $OLD_FIFO_FD -o $fifofd; do
+                    for i in $OLD_PIDS; do
+                        ! kill -0 $i 2>/dev/null && OLD_PIDS=(${OLD_PIDS[@]#i})
+                    done
+                    [[ -z $OLD_PIDS ]] && break
+                done
+                print "0" >&$fifofd ) &
+            fi
+        fi
+        unset OLD_FIFO OLD_FIFO_FD OLD_PIDS
+
+        exec czhttpd_main
+    }
+
+    trap "cleanup 2>/dev/null; exit" INT KILL TERM
+    http_listen
+
+    while :; do
+        # Use select to block until a child writes to fifo on exit
+        while (( ${#jobstates} >= $MAX_CONN - $CACHE )); do
+            log_f "max connections hit, temporarily unable to fork"
+            zselect -r $fifofd && break
+        done
+
+        ztcp -a $listenfd
+
+        ( trap "child_cleanup 2>/dev/null" KILL TERM EXIT; trap '' CHLD PIPE
+
+        function child_cleanup() {
+            kill -9 $coproc_pid; ztcp -c
+            print "0" >&$fifofd
+        }
+
+        fd=$REPLY
+
+        # Use coproc to filter stderr from `srv` and preserve proper pid
+        # for logs.
+        coproc { for ((;;)); zselect -r 0 && <&0 }
+        coproc_pid=$!
+
+        while read ip_line; do
+            [[ $ip_line[3] == "I" ]] && { local client_ip=${ip_line[(ws. .)3]}; break }
+        done < <(ztcp -L)
+
+        if [[ $client_ip =~ [^$IP_ACCEPT]  && $client_ip != "0.0.0.0" ]]; then
+            log_f "disconnected client matching filter $i"
+            exit
+        fi
+
+        while parse_request && check_request; do
+            srv 1>&$fd 2>&p
+
+            if [[ $? != 0 ]]; then
+                sysread errbuff <&p && log_err "${(M)errbuff##*[[:alnum:]]}"
+                log_err "closing socket"
+                break
+            fi
+
+            [[ $HTTP_KEEP_ALIVE == 0 || $req_headers[connection] == "close" ]] && break
+        done
+        child_cleanup) &
+
+        ztcp -c $REPLY
     done
 }
 
-function TRAPHUP() {
-    log_f "Reloading config"
-    if kill -0 $CACHE_WORKER_PID 2>/dev/null; then
-        kill -9 $CACHE_WORKER_PID
-    fi
-    ztcp -c
-
-    shift
-    source $SCRIPT
-}
-
-### Main
-trap "cleanup 2>/dev/null; exit" INT KILL TERM
-
-readonly SCRIPT="$0:A"
-LOG_FORMAT=( '[$(strftime "%a %d %b, %H:%M:%S" $EPOCHSECONDS)]'
-             '[pid: $sysparams[pid]]'
-             '$client_ip'
-             '$req_headers[method]'
-             '$req_headers[url]'
-             '$req_headers[version]' )
-readonly LOG_FORMAT
-
-# Parse cli options and config file
-parse_args $*
-
-# Set our default variables
-log_f "MAXCONN: ${MAX_CONN:=12}"
-log_f "PORT: ${PORT:=8080}"
-log_f "IP_REDIRECT: ${IP_REDIRECT:=$(ip_addr)}"
-log_f "IP_ACCEPT: ${IP_ACCEPT:=[0-9*].[0-9*].[0-9*].[0-9*]}"
-log_f "HTTP_KEEP_ALIVE: ${HTTP_KEEP_ALIVE:=1}"
-log_f "INDEX_FILE: ${INDEX_FILE:=index.html}"
-log_f "HIDDEN_FILES: ${HIDDEN_FILES:=0}"
-log_f "FOLLOW_SYMLINKS: ${FOLLOW_SYMLINKS:=0}"
-log_f "CACHE: ${CACHE:=0}"
-log_f "CACHE_DIR: ${CACHE_DIR:=/tmp/.czhttpd-$$/}"
-log_f "LOG_DIR: ${LOG_DIR:=/dev/null}"
-log_f "FIFO_DIR: ${FIFO_DIR:=/tmp}"
-
-readonly SERVER_NAME="$IP_REDIRECT"
-readonly SERVER_ADDR="$SERVER_NAME"
-readonly SERVER_SOFTWARE="czhttpd/$(printf '%.1f\n' "$((RANDOM/10000.0))")b"
-readonly SERVER_PROTOCOL="HTTP/1.1"
-readonly GATEWAY_INTERFACE="CGI/1.1"
-
-if [[ -z $MTYPES ]]; then
-    MTYPES=( pdf       application/pdf
-            gz        application/x-gzip
-            tar.gz    application/x-tgz
-            tgz       application/x-tgz
-            tar       application/x-tar
-            zip       application/zip
-            gif       image/gif
-            jpeg      image/jpeg
-            jpg       image/jpeg
-            png       image/png
-            css       text/css
-            html      text/html
-            htm       text/html
-            js        text/javascript
-            sh        text/plain
-            py        text/plain
-            pl        text/plain
-            log       text/plain
-            conf      text/plain
-            text      text/plain
-            txt       text/plain
-            default   application/octet-stream )
-fi
-
-http_listen
-
-# For communication with our child processes
-FIFO=$FIFO_DIR/czhttpd-$$.fifo
-if [[ ! -p $FIFO ]]; then
-    mkfifo $FIFO 2>/dev/null || error "Can not create fifo, $FIFO"
-fi
-exec {fifofd}<>$FIFO
-
-# For monitoring when our cache becomes invalid
-(( $CACHE )) && { CACHE_WORKER_PID=$(spawn_cache_worker) || error "Failed to initialise cache_worker" }
-
-while :; do
-    # Use select to block until a child writes to fifo on exit
-    while (( ${#jobstates} >= $MAX_CONN )); do
-        log_f "max connections hit, temporarily unable to fork"
-        zselect -r $fifofd && break
-    done
-
-    ztcp -a $listenfd
-
-    ( trap "ztcp -c; exit" KILL TERM; trap '' PIPE
-
-    fd=$REPLY
-
-    while read ip_line; do
-        [[ $ip_line[3] == "I" ]] && { client_ip=${ip_line[(ws. .)3]}; break }
-    done < <(ztcp -L)
-
-    if [[ $client_ip =~ [^$IP_ACCEPT]  && $client_ip != "0.0.0.0" ]]; then
-        log_f "disconnected client matching filter $i"
-        ztcp -c
-        print "0" >&$fifofd
-        exit 1
-    fi
-
-    while parse_request && check_request; do
-        # Use a pipe since process substitution, >(...), spawns a subprocess so $buff would not
-        # be available to our shell instance. Also, >(sysread buff && log_err $buff) doesn't work
-        # (subshell not getting a copy of errfd?).
-        srv 2>&1 >&$fd | sysread buff
-        lstatus=$pipestatus[1]
-
-        [[ -n $buff ]] && { log_err "${(M)buff##*[[:alnum:]]}"; unset buff }
-
-        [[ $lstatus != 0 ]] && { log_err "broken socket, closing"; break }
-        [[ $HTTP_KEEP_ALIVE == 0 || $req_headers[connection] == "close" ]] && break
-    done
-
-    ztcp -c
-
-    # Write junk to our fifo to indicate to the parent process that our child will soon exit
-    print "0" >&$fifofd ) &
-
-    ztcp -c $REPLY
-done
+czhttpd_init $* && czhttpd_main
